numpy

In [1]:
import time
from sys import getsizeof as size
import numpy as np

In [3]:
#creating a linespace(evenly distributed array)
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [2]:
#create an array with same integers and change datatype
np.full((3,3),12,dtype=np.float32)

array([[12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.]], dtype=float32)

In [10]:
#create an identity matrix
x=np.identity(3)
y=np.eye(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
np.zeros((3,3),dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [23]:
#creating a three dimensional array
np.random.randint(10,size=(3,4,3))

array([[[8, 3, 2],
        [3, 9, 5],
        [8, 3, 9],
        [5, 8, 0]],

       [[1, 0, 3],
        [7, 7, 8],
        [8, 3, 9],
        [9, 6, 5]],

       [[2, 5, 5],
        [7, 2, 0],
        [9, 2, 0],
        [2, 7, 5]]])

In [33]:
a=np.array([[[2,3,77,25],[54,555,556,5,66,55,66,5],[25,23]]])

In [34]:
np.ndim(a)

2

In [4]:
a=np.random.randint(0,20,(3,3))
a

array([[ 2,  4,  4],
       [ 4, 18, 12],
       [ 7,  8, 13]])

In [69]:
a[2::-1,2::-1]

array([[17,  0, 13],
       [14, 17, 13],
       [ 7, 12,  5]])

In [93]:
a[0::,0].std()

3.7712361663282534

In [92]:
np.average(a[0::,0])

10.333333333333334

In [88]:
a[0::,0]

array([ 5, 13, 13])

In [94]:
np.average()t 

3.6666666666666665

In [98]:
np.ones((3,3),dtype=np.int8) 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [35]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [6]:
print(a)
amini=a[:2,:1]

[[ 2  4  4]
 [ 4 18 12]
 [ 7  8 13]]


In [10]:
amini[1,0]=25

In [11]:
a
#here changes are made even though a is not touched.while if we used copy keyword it would't have changed

array([[ 2,  4,  4],
       [25, 18, 12],
       [ 7,  8, 13]])

In [18]:
# reshaping of array
print('shape of a =',a.shape)
print(a.reshape(1,9))
print(a)
#it doesn't change shape of a. we could do a= a.reshape(x,y)

shape of a = (3, 3)
[[ 2  4  4 25 18 12  7  8 13]]
[[ 2  4  4]
 [25 18 12]
 [ 7  8 13]]


In [15]:
#concatenation
x= np.array([[1,2,8,5],[14,1,55,24]])
y=np.random.randint(1,6,(2,4))
print(np.concatenate([x,y]))
#here axis 1 or 0 decides whether the concatenation is to be done horizontally or vertically
z=np.hstack([x,y])# or v stack depends on how u want to do cocatenation
print(z)

[[ 1  2  8  5]
 [14  1 55 24]
 [ 2  5  2  2]
 [ 4  4  3  1]]
[[ 1  2  8  5]
 [14  1 55 24]
 [ 2  5  2  2]
 [ 4  4  3  1]]


In [22]:
#splitting
p,q=np.vsplit(z,[2])

In [25]:
print(p,q)

[[ 1  2  8  5]
 [14  1 55 24]] [[2 5 2 2]
 [4 4 3 1]]
